export const foods = [
  {
    id: 1,
    image: "/assets/apple-juice.webp",
    title: "Apple Juice",
    description:
      "Freshly squeezed Apple juice that is great for your wellbeing.",
    price: 9.99,
    category: "Beverages",
    restaurantName: "Restaurant 1",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 2,
    image: "/assets/Apple-Pie.webp",
    title: "Apple Pie",
    description:
      "Goodness of apples and ice cream with a sprinkle of cinnamon.",
    price: 12.99,
    category: "Desserts",
    restaurantName: "Restaurant 2",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 3,
    image: "/assets/Basil-Soup.webp",
    title: "Basil Soup",
    description: "Description of Food Item 3",
    price: 8.99,
    category: "Soups",
    restaurantName: "Restaurant 3",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 4,
    image: "/assets/Brownie.webp",
    title: "Brownie",
    description: "Description of Food Item 4",
    price: 10.99,
    category: "Desserts",
    restaurantName: "Restaurant 4",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 5,
    image: "/assets/Butter-Chicken.webp",
    title: "Butter Chicken",
    description: "Description of Food Item 5",
    price: 7.99,
    category: "Main Course",
    restaurantName: "Restaurant 5",
    tag: "Non-Veg",
    quantity: 0,
  },
  {
    id: 6,
    image: "/assets/coffee.webp",
    title: "Coffee",
    description: "Description of Food Item 6",
    price: 11.99,
    category: "Beverages",
    restaurantName: "Restaurant 6",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 7,
    image: "/assets/Fried-Chicken.webp",
    title: "Fried Chicken",
    description: "Description of Food Item 7",
    price: 9.49,
    category: "Starters",
    restaurantName: "Restaurant 7",
    tag: "Non-Veg",
    quantity: 0,
  },
  {
    id: 8,
    image: "/assets/Gulab-Jamun.webp",
    title: "Gulab Jamun",
    description: "Description of Food Item 8",
    price: 13.99,
    category: "Desserts",
    restaurantName: "Restaurant 8",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 9,
    image: "/assets/Malai-Kulfi.webp",
    title: "Malai Kulfi",
    description: "Description of Food Item 9",
    price: 6.99,
    category: "Desserts",
    restaurantName: "Restaurant 9",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 10,
    image: "/assets/Mixed-Veggie-Platter.webp",
    title: "Mixed Veggie Platter",
    description: "Description of Food Item 10",
    price: 14.99,
    category: "Starters",
    restaurantName: "Restaurant 10",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 11,
    image: "/assets/Onion-Soup.webp",
    title: "Onion Soup",
    description: "Description of Food Item 11",
    price: 9.99,
    category: "Soups",
    restaurantName: "Restaurant 11",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 12,
    image: "/assets/orange-juice.webp",
    title: "Orange Juice",
    description: "Description of Food Item 12",
    price: 12.99,
    category: "Beverages",
    restaurantName: "Restaurant 12",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 13,
    image: "/assets/Panner-Butter-Masala.webp",
    title: "Panner Butter Masala",
    description: "Description of Food Item 13",
    price: 8.99,
    category: "Main Course",
    restaurantName: "Restaurant 13",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 14,
    image: "/assets/Panner-Manchurian.webp",
    title: "Panner Manchurian",
    description: "Description of Food Item 14",
    price: 10.99,
    category: "Main Course",
    restaurantName: "Restaurant 14",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 15,
    image: "/assets/Steamed-Momos.webp",
    title: "Steamed Momos",
    description: "Description of Food Item 15",
    price: 7.99,
    category: "Starters",
    restaurantName: "Restaurant 15",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 16,
    image: "/assets/tea.webp",
    title: "Tea",
    description: "Description of Food Item 16",
    price: 11.99,
    category: "Beverages",
    restaurantName: "Restaurant 16",
    tag: "Veg",
    quantity: 0,
  },
  {
    id: 17,
    image: "/assets/Tomato-Soup.webp",
    title: "Tomato Soup",
    description: "Description of Food Item 17",
    price: 11.99,
    category: "Soups",
    restaurantName: "Restaurant 16",
    tag: "Veg",
    quantity: 0,
  },
];

export const categories = [
  "Beverages",
  "Starters",
  "Main Course",
  "Soups",
  "Desserts",
];
